# Generated by Django 6.0.6 on 2026-07-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='spice_level',
            field=models.CharField(blank=True, choices=[('mild', 'Mild Spicy'), ('extra', 'Extra Spicy')], default='mild', max_length=10),
        ),
    ]
