# Generated by Django 6.0.6 on 2026-07-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_pendingorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingorder',
            name='delivery_zone',
            field=models.CharField(default='mainland', max_length=20),
        ),
    ]
