# Generated by Django 6.0.6 on 2026-07-05 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_pendingorder_delivery_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_area',
            field=models.CharField(blank=True, help_text='Selected delivery zone/location', max_length=100),
        ),
        migrations.AlterField(
            model_name='pendingorder',
            name='delivery_zone',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
