# Generated by Django 6.0.6 on 2026-07-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_delivery_area_alter_pendingorder_delivery_zone'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(help_text='e.g. Island (Before Sangotedo), Mainland', max_length=100)),
                ('name', models.CharField(help_text='Location shown to the customer', max_length=100, unique=True)),
                ('fee', models.PositiveIntegerField(help_text='Delivery fee in Naira')),
                ('group_order', models.PositiveIntegerField(default=0, help_text='Order the group appears (lower = higher up)')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Order within the group')),
                ('is_active', models.BooleanField(default=True, help_text='Untick to hide from checkout')),
            ],
            options={
                'ordering': ['group_order', 'sort_order', 'name'],
            },
        ),
    ]
