# Generated by Django 6.0.6 on 2026-08-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_seed_delivery_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverylocation',
            name='arrange_privately',
            field=models.BooleanField(default=False, help_text='Customer arranges & pays for delivery themselves (no fixed fee)'),
        ),
        migrations.AlterField(
            model_name='deliverylocation',
            name='fee',
            field=models.PositiveIntegerField(default=0, help_text="Delivery fee in Naira (ignored if 'arrange privately' is on)"),
        ),
    ]
